name: CI

on:
  push: {}
  pull_request:
    branches: [ master, staging ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Use yamllint
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: ./content

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        yarn install
        yarn ci
